/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HealthChecker: typeof import('./src/components/HealthChecker.vue')['default']
    TransactionTable: typeof import('./src/components/TransactionTable.vue')['default']
  }
}
